export const PIX_PAYMENT_EXPIRATION_SECONDS = 5 * 60;
export const PIX_PAYMENT_EXPIRATION_MS = PIX_PAYMENT_EXPIRATION_SECONDS * 1000;
export const PIX_STATUS_POLLING_MS = 10000;
export const CARD_BRAND_CACHE_TTL_MS = 24 * 60 * 60 * 1000;
